language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  email: david@stabbylambda.com
  skip_cleanup: true
  api_key:
    secure: mVtgxOLtJPJ7wI3xJCqt+kR8rz5wlEupQulQ5JtoJW2YlGWgoNMmGS9QkYpKQIlF4x1oAdjK8GzM90Dazk4kUiPQlSMwyHdjmwGPj0BM7JdE+ixRsLQKyn/Oq/pri7BM25hQLPb6WkJlX611UQz0sxAlfidjQF6tHPV3yCR9MWl9Oe5xAemImBOWuMtxZChuPHmi73j7fu74hK8VDcUDQKV0hTlTYfONI2Zrj1h20H9XuXkMj6yBrRcPGWiSvOQkYcr1eDVnoGyI88/QXibwNHiq6gqXi7I1P//vCdlyuStaiaUdOzfZm3IwvjkX1uI931A0yRRe6ox4usUzWLz+AUFIXTjN4dlPRS1Y7oJHxaQFWB/RT10fSEwvkXCR77sULL3SYwtfsw53AO6UW30jSEyPHUI58uxq8V0/hFG5MivxnP3Uyk2MrkLx/CPNgq9C2aNZoD/RJLA1LG36bmPLw41kepRrmGDba4WGsdoEiXIvHZUl3WSLGugXWnent12QHRWRWiE9q+GttLxhJY8RCwNfgDsiBVQEYcBi1vGO5WiqPBzGMEuqTVzzsjxMq+7c/EM2JODmbGEP1EoBsMuPpzttUBNVFg6A6avMhcMx2fS/KITQhyLH76AELuixVkphn40jsZ1GcdMk5D/lg++e97XfoqP3kOJ52rY3iVp2b+k=
  on:
    tags: true
    repo: stabbylambda/quietcool
